version: "3"

services:
  postgresql:
    image: postgres
    restart: always
    container_name: bmvp_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bmvp_dev
    volumes:
      - bmvp_db:/var/lib/postgresql/data

volumes:
  bmvp_db:
